/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'wallet' : IDL.Nat,
});
export const WalletTransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const WalletTransaction = IDL.Record({
  'id' : IDL.Nat,
  'status' : WalletTransactionStatus,
  'transactionType' : IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const MatchStatus = IDL.Variant({
  'completed' : IDL.Null,
  'waiting' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'player' : IDL.Principal,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllUsersWithWalletOver' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAllWalletTransactions' : IDL.Func(
      [],
      [IDL.Vec(WalletTransaction)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getPendingPayments' : IDL.Func([], [IDL.Vec(WalletTransaction)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
  'getUsersSortedByWallet' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], []),
  'getWithdrawals' : IDL.Func([], [IDL.Vec(WalletTransaction)], ['query']),
  'hasUserTransaction' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
      ],
      [IDL.Bool],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func([], [], []),
  'login' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'requestWithdraw' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPayment' : IDL.Func([IDL.Nat], [], []),
  'updateWalletTransactionStatus' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'wallet' : IDL.Nat,
  });
  const WalletTransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const WalletTransaction = IDL.Record({
    'id' : IDL.Nat,
    'status' : WalletTransactionStatus,
    'transactionType' : IDL.Variant({
      'deposit' : IDL.Null,
      'withdrawal' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const MatchStatus = IDL.Variant({
    'completed' : IDL.Null,
    'waiting' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'player' : IDL.Principal,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllUsersWithWalletOver' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAllWalletTransactions' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [UserProfile], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getPendingPayments' : IDL.Func(
        [],
        [IDL.Vec(WalletTransaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getUserProfileByUsername' : IDL.Func([IDL.Text], [UserProfile], ['query']),
    'getUsersSortedByWallet' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], []),
    'getWithdrawals' : IDL.Func([], [IDL.Vec(WalletTransaction)], ['query']),
    'hasUserTransaction' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'deposit' : IDL.Null, 'withdrawal' : IDL.Null }),
        ],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func([], [], []),
    'login' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'requestWithdraw' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPayment' : IDL.Func([IDL.Nat], [], []),
    'updateWalletTransactionStatus' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };