/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'player' : Principal,
  'timestamp' : Time,
}
export type MatchStatus = { 'completed' : null } |
  { 'waiting' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile {
  'username' : string,
  'password' : string,
  'wallet' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : bigint,
  'status' : WalletTransactionStatus,
  'transactionType' : { 'deposit' : null } |
    { 'withdrawal' : null },
  'user' : Principal,
  'timestamp' : Time,
  'amount' : bigint,
}
export type WalletTransactionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getAllUsersWithWalletOver' : ActorMethod<[bigint], Array<UserProfile>>,
  'getAllWalletTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  /**
   * / Returns the caller's user profile.
   */
  'getCallerUserProfile' : ActorMethod<[], UserProfile>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatches' : ActorMethod<[], Array<Match>>,
  'getPendingPayments' : ActorMethod<[], Array<WalletTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], UserProfile>,
  'getUserProfileByUsername' : ActorMethod<[string], UserProfile>,
  'getUsersSortedByWallet' : ActorMethod<[], Array<UserProfile>>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'getWithdrawals' : ActorMethod<[], Array<WalletTransaction>>,
  'hasUserTransaction' : ActorMethod<
    [Principal, { 'deposit' : null } | { 'withdrawal' : null }],
    boolean
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRegistered' : ActorMethod<[Principal], boolean>,
  'joinMatch' : ActorMethod<[], undefined>,
  /**
   * / Returns true if the input password matches the user's password.
   */
  'login' : ActorMethod<[string], boolean>,
  /**
   * / Registers a new user profile with the provided username and password.
   */
  'register' : ActorMethod<[string, string], undefined>,
  'requestWithdraw' : ActorMethod<[bigint], undefined>,
  /**
   * / Saves the user profile for the caller.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPayment' : ActorMethod<[bigint], undefined>,
  'updateWalletTransactionStatus' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];