/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Clan {
    id: string;
    members: Array<string>;
    leaderId: string;
    name: string;
    createdAt: bigint;
}
export interface UserPublic {
    uid: string;
    lastLoginDate: string;
    referralCode: string;
    fcmToken: string;
    lastLoginAt: bigint;
    loginStreak: bigint;
    kycVerified: boolean;
    name: string;
    createdAt: bigint;
    coins: bigint;
    totalWins: bigint;
    loyaltyPoints: bigint;
    banReason: string;
    referredBy: string;
    birthMonth: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    vipTier: string;
    totalKills: bigint;
    walletBalance: number;
    totalMatchesPlayed: bigint;
}
export interface Tournament {
    id: string;
    startTime: bigint;
    status: string;
    registeredPlayers: Array<string>;
    name: string;
    createdAt: bigint;
    winner: string;
    entryFee: number;
    prizePool: number;
}
export interface Message {
    id: string;
    createdAt: bigint;
    text: string;
    imageUrl: string;
    senderName: string;
    category: string;
    isPinned: boolean;
    reactions: Array<[string, string]>;
    senderId: string;
}
export interface Match {
    id: string;
    status: string;
    title: string;
    voiceChannelLink: string;
    scheduledTime: string;
    mode: string;
    createdAt: bigint;
    winner: string;
    perKill: number;
    roomPassword: string;
    currentPlayers: bigint;
    isHidden: boolean;
    entryFee: number;
    joinedPlayers: Array<[string, string]>;
    roomId: string;
    kills: Array<[string, bigint]>;
    maxPlayers: bigint;
    prizePool: number;
    adminProfit: number;
}
export interface UserAdmin {
    uid: string;
    lastLoginDate: string;
    referralCode: string;
    lastLoginAt: bigint;
    loginStreak: bigint;
    kycVerified: boolean;
    name: string;
    createdAt: bigint;
    coins: bigint;
    totalWins: bigint;
    loyaltyPoints: bigint;
    banReason: string;
    referredBy: string;
    birthMonth: bigint;
    isBanned: boolean;
    isAdmin: boolean;
    phone: string;
    vipTier: string;
    totalKills: bigint;
    walletBalance: number;
    totalMatchesPlayed: bigint;
}
export interface Report {
    id: string;
    createdAt: bigint;
    reportedId: string;
    reporterId: string;
    reason: string;
}
export interface Transaction {
    id: string;
    uid: string;
    status: string;
    note: string;
    createdAt: bigint;
    coins: bigint;
    upiId: string;
    txType: string;
    amount: number;
}
export interface backendInterface {
    adminAdjustCoins(adminUid: string, targetUid: string, coins: bigint): Promise<void>;
    adminAdjustWallet(adminUid: string, targetUid: string, amount: number, note: string): Promise<void>;
    adminAssignKills(adminUid: string, matchId: string, killData: Array<[string, bigint]>): Promise<void>;
    adminBanUser(adminUid: string, targetUid: string, reason: string): Promise<void>;
    adminCreateMatch(adminUid: string, mode: string, title: string, entryFee: number, prizePool: number, perKill: number, maxPlayers: bigint, scheduledTime: string): Promise<string>;
    adminCreateTournament(adminUid: string, name: string, entryFee: number, prizePool: number, startTime: bigint): Promise<string>;
    adminDeclareTournamentWinner(adminUid: string, tournamentId: string, winnerUid: string): Promise<void>;
    adminDeclareWinner(adminUid: string, matchId: string, winnerUid: string): Promise<void>;
    adminGetAllMatches(adminUid: string): Promise<Array<Match>>;
    adminGetAllTransactions(adminUid: string): Promise<Array<Transaction>>;
    adminGetAllUsers(adminUid: string): Promise<Array<UserAdmin>>;
    adminGetReports(adminUid: string): Promise<Array<Report>>;
    adminGetRevenue(adminUid: string): Promise<{
        totalCollected: number;
        totalWithdrawals: number;
        totalPrizesPaid: number;
        totalDeposits: number;
        netProfit: number;
    }>;
    adminPinMessage(adminUid: string, msgId: string, pin: boolean): Promise<void>;
    adminSendMessage(adminUid: string, text: string, category: string, imageUrl: string, isPinned: boolean): Promise<string>;
    adminSetKyc(adminUid: string, targetUid: string, verified: boolean): Promise<void>;
    adminSetMatchRoom(adminUid: string, matchId: string, roomId: string, roomPassword: string): Promise<void>;
    adminSetVoiceLink(adminUid: string, matchId: string, link: string): Promise<void>;
    adminToggleMatchVisibility(adminUid: string, matchId: string): Promise<void>;
    adminUnbanUser(adminUid: string, targetUid: string): Promise<void>;
    adminUpdateMatchStatus(adminUid: string, matchId: string, status: string): Promise<void>;
    adminUpdateTransaction(adminUid: string, txId: string, status: string): Promise<void>;
    createClan(uid: string, name: string): Promise<string>;
    getClans(): Promise<Array<Clan>>;
    getLeaderboard(): Promise<Array<UserPublic>>;
    getMatch(matchId: string): Promise<Match | null>;
    getMatches(): Promise<Array<Match>>;
    getMessages(): Promise<Array<Message>>;
    getMyProfile(uid: string): Promise<UserPublic | null>;
    getTournaments(): Promise<Array<Tournament>>;
    getUserTransactions(uid: string): Promise<Array<Transaction>>;
    joinClan(uid: string, clanId: string): Promise<string>;
    joinMatch(uid: string, matchId: string): Promise<string>;
    login(uid: string, password: string): Promise<[UserPublic | null, string]>;
    reactToMessage(uid: string, msgId: string, emoji: string): Promise<void>;
    registerForTournament(uid: string, tournamentId: string): Promise<string>;
    registerUser(uid: string, password: string, name: string, phone: string, referredBy: string): Promise<string>;
    reportPlayer(reporterId: string, reportedId: string, reason: string): Promise<void>;
    submitDeposit(uid: string, amount: number, upiId: string): Promise<string>;
    submitWithdrawal(uid: string, amount: number, upiId: string): Promise<string>;
    updateFcmToken(uid: string, token: string): Promise<void>;
    updateProfile(uid: string, name: string, phone: string, birthMonth: bigint): Promise<void>;
}
import type { Match as _Match, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAdjustCoins(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustCoins(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustCoins(arg0, arg1, arg2);
            return result;
        }
    }
    async adminAdjustWallet(arg0: string, arg1: string, arg2: number, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAdjustWallet(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAdjustWallet(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminAssignKills(arg0: string, arg1: string, arg2: Array<[string, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAssignKills(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAssignKills(arg0, arg1, arg2);
            return result;
        }
    }
    async adminBanUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanUser(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreateMatch(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: number, arg6: bigint, arg7: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateMatch(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateMatch(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async adminCreateTournament(arg0: string, arg1: string, arg2: number, arg3: number, arg4: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTournament(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTournament(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminDeclareTournamentWinner(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeclareTournamentWinner(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeclareTournamentWinner(arg0, arg1, arg2);
            return result;
        }
    }
    async adminDeclareWinner(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeclareWinner(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeclareWinner(arg0, arg1, arg2);
            return result;
        }
    }
    async adminGetAllMatches(arg0: string): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllMatches(arg0);
            return result;
        }
    }
    async adminGetAllTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllTransactions(arg0);
            return result;
        }
    }
    async adminGetAllUsers(arg0: string): Promise<Array<UserAdmin>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers(arg0);
            return result;
        }
    }
    async adminGetReports(arg0: string): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetReports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetReports(arg0);
            return result;
        }
    }
    async adminGetRevenue(arg0: string): Promise<{
        totalCollected: number;
        totalWithdrawals: number;
        totalPrizesPaid: number;
        totalDeposits: number;
        netProfit: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetRevenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetRevenue(arg0);
            return result;
        }
    }
    async adminPinMessage(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminPinMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminPinMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async adminSendMessage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSendMessage(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSendMessage(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async adminSetKyc(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetKyc(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetKyc(arg0, arg1, arg2);
            return result;
        }
    }
    async adminSetMatchRoom(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetMatchRoom(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetMatchRoom(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async adminSetVoiceLink(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetVoiceLink(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetVoiceLink(arg0, arg1, arg2);
            return result;
        }
    }
    async adminToggleMatchVisibility(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminToggleMatchVisibility(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminToggleMatchVisibility(arg0, arg1);
            return result;
        }
    }
    async adminUnbanUser(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnbanUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnbanUser(arg0, arg1);
            return result;
        }
    }
    async adminUpdateMatchStatus(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateMatchStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateMatchStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateTransaction(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateTransaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateTransaction(arg0, arg1, arg2);
            return result;
        }
    }
    async createClan(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createClan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClan(arg0, arg1);
            return result;
        }
    }
    async getClans(): Promise<Array<Clan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClans();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMatch(arg0: string): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatches();
            return result;
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getMyProfile(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournaments(): Promise<Array<Tournament>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournaments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournaments();
            return result;
        }
    }
    async getUserTransactions(arg0: string): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTransactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTransactions(arg0);
            return result;
        }
    }
    async joinClan(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.joinClan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinClan(arg0, arg1);
            return result;
        }
    }
    async joinMatch(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatch(arg0, arg1);
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<[UserPublic | null, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return [
                    from_candid_opt_n2(this._uploadFile, this._downloadFile, result[0]),
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return [
                from_candid_opt_n2(this._uploadFile, this._downloadFile, result[0]),
                result[1]
            ];
        }
    }
    async reactToMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reactToMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reactToMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async registerForTournament(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForTournament(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForTournament(arg0, arg1);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async reportPlayer(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reportPlayer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportPlayer(arg0, arg1, arg2);
            return result;
        }
    }
    async submitDeposit(arg0: string, arg1: number, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeposit(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeposit(arg0, arg1, arg2);
            return result;
        }
    }
    async submitWithdrawal(arg0: string, arg1: number, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFcmToken(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFcmToken(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFcmToken(arg0, arg1);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
